name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install elan (Lean toolchain)
        shell: bash
        run: |
          curl -sSf https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | sh -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Show versions
        run: |
          ~/.elan/bin/lean --version || true
          ~/.elan/bin/lake --version || true

      - name: Lake update
        run: ~/.elan/bin/lake update

      - name: Lake build
        run: ~/.elan/bin/lake build
